using System;
using System.Collections.Generic;
using System.Linq;
using OpenAutoMapper.Generator.Helpers;
using OpenAutoMapper.Generator.Models;

namespace OpenAutoMapper.Generator.Pipeline;

/// <summary>
/// Stage 3: Emits mapping extension methods for each type pair.
/// </summary>
internal static class MappingCodeEmitter
{
    public static string? EmitMappingExtension(TypePairDescriptor typePair)
    {
        if (typePair.PropertyMatches.Length == 0 && !typePair.IsPolymorphicBase && typePair.ConvertUsingExpression is null && !typePair.HasConstructorMapping)
            return null;

        _emitDeepClone = typePair.IsDeepClone;

        var sb = new SourceStringBuilder();

        var needsCollections = typePair.PropertyMatches.Any(m =>
            m.ConversionKind == ConversionKind.Collection);
        var needsDictionary = typePair.PropertyMatches.Any(m =>
            m.ConversionKind == ConversionKind.Dictionary);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        if (needsCollections || needsDictionary)
        {
            sb.AppendLine("using System.Collections.Generic;");
        }
        if (needsCollections)
        {
            sb.AppendLine("using System.Linq;");
        }
        sb.AppendLine();

        // Determine namespace from destination type
        var destNamespace = GetNamespace(typePair.DestFullName);
        var hasNamespace = !string.IsNullOrEmpty(destNamespace);

        if (hasNamespace)
        {
            sb.AppendLine($"namespace {destNamespace};");
            sb.AppendLine();
        }

        var nameSuffix = typePair.MappingName is not null ? "_" + SanitizeName(typePair.MappingName) : "";
        var className = $"{typePair.SourceName}To{typePair.DestName}{nameSuffix}MappingExtensions";
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Auto-generated mapping extensions from <see cref=\"{EscapeXmlComment(typePair.SourceFullName)}\"/> to <see cref=\"{EscapeXmlComment(typePair.DestFullName)}\"/>.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"OpenAutoMapper.Generator\", \"1.0.0.0\")]");
        sb.AppendLine($"public static class {className}");
        sb.OpenBrace();

        // Emit ThreadStatic depth field for circular references
        if (typePair.HasCyclicReference)
        {
            var fieldName = GetDepthFieldName(typePair);
            sb.AppendLine("[ThreadStatic]");
            sb.AppendLine($"private static int {fieldName};");
            sb.AppendLine();
        }

        EmitMapToMethod(sb, typePair);

        // Emit multi-source overload if IncludeSource was used
        if (typePair.AdditionalSourceTypes.Length > 0)
        {
            sb.AppendLine();
            EmitMultiSourceMapMethod(sb, typePair);
        }

        sb.CloseBrace();

        return sb.ToString();
    }

    internal static string GetMapMethodName(TypePairDescriptor typePair)
    {
        var nameSuffix = typePair.MappingName is not null ? "_" + SanitizeName(typePair.MappingName) : "";
        return $"MapTo{typePair.DestName}{nameSuffix}";
    }

    private static void EmitMapToMethod(SourceStringBuilder sb, TypePairDescriptor typePair)
    {
        var methodName = GetMapMethodName(typePair);
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Maps a <see cref=\"{EscapeXmlComment(typePair.SourceFullName)}\"/> to a new <see cref=\"{EscapeXmlComment(typePair.DestFullName)}\"/>.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public static {typePair.DestFullName} {methodName}(this {typePair.SourceFullName} source)");
        sb.OpenBrace();

        sb.AppendLine("if (source is null)");
        sb.Indent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(source));");
        sb.Unindent();
        sb.AppendLine();

        // Depth tracking for circular references
        if (typePair.HasCyclicReference)
        {
            var fieldName = GetDepthFieldName(typePair);
            sb.AppendLine($"if ({fieldName} >= {typePair.MaxDepth})");
            sb.Indent();
            sb.AppendLine("return default!;");
            sb.Unindent();
            sb.AppendLine();
            sb.AppendLine($"{fieldName}++;");
            sb.AppendLine("try");
            sb.OpenBrace();
        }

        // ConvertUsing replaces the entire mapping
        if (typePair.ConvertUsingExpression is not null)
        {
            sb.AppendLine($"return ((global::OpenAutoMapper.ITypeConverter<{typePair.SourceFullName}, {typePair.DestFullName}>)({typePair.ConvertUsingExpression})).Convert(source, default!, default!);");

            // Close depth tracking try/finally if needed
            if (typePair.HasCyclicReference)
            {
                sb.CloseBrace();
                sb.AppendLine("finally");
                sb.OpenBrace();
                var depthField = GetDepthFieldName(typePair);
                sb.AppendLine($"{depthField}--;");
                sb.CloseBrace();
            }

            sb.CloseBrace();
            return;
        }

        bool hasConstructUsing = typePair.ConstructUsingExpression is not null;
        bool hasBeforeMap = typePair.BeforeMapExpression is not null;
        bool hasAfterMap = typePair.AfterMapExpression is not null;
        bool hasConditions = typePair.PropertyMatches.Any(m =>
            m.ConditionExpression is not null || m.PreConditionExpression is not null);
        bool hasDottedPaths = typePair.PropertyMatches.Any(m =>
            m.DestPropertyName.Contains("."));
        bool hasCtorParams = typePair.HasConstructorMapping;
        bool hasInitOnly = typePair.PropertyMatches.Any(m => m.IsInitOnly);
        bool hasMutableProps = typePair.PropertyMatches.Any(m => !m.IsInitOnly && !m.DestPropertyName.Contains("."));
        bool needsTwoPass = hasConstructUsing || hasAfterMap || hasBeforeMap || hasConditions || hasDottedPaths || hasCtorParams;

        // Polymorphic switch
        if (typePair.IsPolymorphicBase)
        {
            sb.AppendLine("return source switch");
            sb.OpenBrace();

            foreach (var derived in typePair.IncludedDerivedTypes)
            {
                var varName = $"derived{derived.SourceName}";
                sb.AppendLine($"{derived.SourceFullName} {varName} => {varName}.MapTo{derived.DestName}(),");
            }

            // Default arm: base mapping
            if (typePair.PropertyMatches.Length > 0 || hasCtorParams)
            {
                EmitPolymorphicDefaultArm(sb, typePair);
            }
            else
            {
                sb.AppendLine($"_ => new {typePair.DestFullName}()");
            }

            sb.CloseBraceWithSemicolon();
        }
        else if (needsTwoPass)
        {
            // Hybrid emission: ctor args + init-only in initializer + mutable via assignment
            if (hasConstructUsing)
            {
                sb.AppendLine($"var result = ((global::System.Func<{typePair.SourceFullName}, {typePair.DestFullName}>)({typePair.ConstructUsingExpression}))(source);");
            }
            else
            {
                EmitConstructionWithInitializer(sb, typePair);
            }

            if (hasBeforeMap)
            {
                sb.AppendLine($"((global::System.Action<{typePair.SourceFullName}, {typePair.DestFullName}>)({typePair.BeforeMapExpression}))(source, result);");
            }

            // Emit mutable property assignments (skip init-only — they were in the initializer)
            EmitPropertyAssignments(sb, typePair, "source", "result");

            if (hasAfterMap)
            {
                sb.AppendLine($"((global::System.Action<{typePair.SourceFullName}, {typePair.DestFullName}>)({typePair.AfterMapExpression}))(source, result);");
            }

            sb.AppendLine("return result;");
        }
        else if (hasInitOnly)
        {
            // All properties can go in initializer (no conditions, no dotted paths)
            sb.AppendLine($"return new {typePair.DestFullName}");
            sb.OpenBrace();
            EmitPropertyInitializer(sb, typePair);
            sb.CloseBraceWithSemicolon();
        }
        else
        {
            sb.AppendLine($"return new {typePair.DestFullName}");
            sb.OpenBrace();
            EmitPropertyInitializer(sb, typePair);
            sb.CloseBraceWithSemicolon();
        }

        // Close depth tracking try/finally
        if (typePair.HasCyclicReference)
        {
            sb.CloseBrace(); // close try
            sb.AppendLine("finally");
            sb.OpenBrace();
            var fieldName = GetDepthFieldName(typePair);
            sb.AppendLine($"{fieldName}--;");
            sb.CloseBrace(); // close finally
        }

        sb.CloseBrace();
    }

    private static void EmitPropertyInitializer(SourceStringBuilder sb, TypePairDescriptor typePair)
    {
        for (int i = 0; i < typePair.PropertyMatches.Length; i++)
        {
            var match = typePair.PropertyMatches[i];
            var comma = i < typePair.PropertyMatches.Length - 1 ? "," : "";
            var assignment = EmitPropertyAssignment(match, typePair.AllowNullCollections);
            sb.AppendLine($"{match.DestPropertyName} = {assignment}{comma}");
        }
    }

    /// <summary>
    /// Emits: var result = new Dest(ctorArg1, ctorArg2) { InitProp = val };
    /// Init-only properties without conditions go in the initializer.
    /// </summary>
    private static void EmitConstructionWithInitializer(SourceStringBuilder sb, TypePairDescriptor typePair)
    {
        // Build constructor arguments
        var ctorArgs = new System.Text.StringBuilder();
        for (int i = 0; i < typePair.ConstructorParams.Length; i++)
        {
            if (i > 0) ctorArgs.Append(", ");
            var param = typePair.ConstructorParams[i];
            ctorArgs.Append(EmitCtorParamConversion(param, "source"));
        }

        // Collect init-only properties that have no conditions (they go in initializer)
        var initOnlyProps = new List<(PropertyMatchDescriptor match, string assignment)>();
        foreach (var match in typePair.PropertyMatches)
        {
            if (match.IsInitOnly && match.ConditionExpression is null && match.PreConditionExpression is null
                && !match.DestPropertyName.Contains("."))
            {
                initOnlyProps.Add((match, EmitPropertyAssignment(match, typePair.AllowNullCollections)));
            }
        }

        if (initOnlyProps.Count > 0)
        {
            sb.AppendLine($"var result = new {typePair.DestFullName}({ctorArgs})");
            sb.OpenBrace();
            for (int i = 0; i < initOnlyProps.Count; i++)
            {
                var (match, assignment) = initOnlyProps[i];
                var comma = i < initOnlyProps.Count - 1 ? "," : "";
                sb.AppendLine($"{match.DestPropertyName} = {assignment}{comma}");
            }
            sb.CloseBraceWithSemicolon();
        }
        else
        {
            sb.AppendLine($"var result = new {typePair.DestFullName}({ctorArgs});");
        }
    }

    /// <summary>
    /// Emits the polymorphic default arm with constructor + initializer support.
    /// </summary>
    private static void EmitPolymorphicDefaultArm(SourceStringBuilder sb, TypePairDescriptor typePair)
    {
        if (typePair.HasConstructorMapping)
        {
            var ctorArgs = new System.Text.StringBuilder();
            for (int i = 0; i < typePair.ConstructorParams.Length; i++)
            {
                if (i > 0) ctorArgs.Append(", ");
                var param = typePair.ConstructorParams[i];
                ctorArgs.Append(EmitCtorParamConversion(param, "source"));
            }

            if (typePair.PropertyMatches.Length > 0)
            {
                sb.AppendLine($"_ => new {typePair.DestFullName}({ctorArgs})");
                sb.OpenBrace();
                EmitPropertyInitializer(sb, typePair);
                sb.CloseBrace();
            }
            else
            {
                sb.AppendLine($"_ => new {typePair.DestFullName}({ctorArgs})");
            }
        }
        else
        {
            sb.AppendLine($"_ => new {typePair.DestFullName}");
            sb.OpenBrace();
            EmitPropertyInitializer(sb, typePair);
            sb.CloseBrace();
        }
    }

    private static string EmitCtorParamConversion(Models.ConstructorParamDescriptor param, string sourceVar)
    {
        var sourceAccess = $"{sourceVar}.{param.SourcePropertyName}";
        switch (param.ConversionKind)
        {
            case Models.ConversionKind.Direct:
            case Models.ConversionKind.ImplicitCast:
                return sourceAccess;
            case Models.ConversionKind.ExplicitCast:
                return $"({param.ParamType}){sourceAccess}";
            case Models.ConversionKind.ToString:
                return $"{sourceAccess}.ToString()";
            default:
                return sourceAccess;
        }
    }

    private static void EmitPropertyAssignments(SourceStringBuilder sb, TypePairDescriptor typePair, string sourceVar, string destVar)
    {
        // Track which intermediate paths have been initialized (for ??= new)
        var initializedPaths = new HashSet<string>(StringComparer.Ordinal);

        for (int i = 0; i < typePair.PropertyMatches.Length; i++)
        {
            var match = typePair.PropertyMatches[i];

            // Skip init-only properties without conditions (they were emitted in the initializer)
            if (match.IsInitOnly && match.ConditionExpression is null && match.PreConditionExpression is null
                && !match.DestPropertyName.Contains("."))
                continue;

            // Init-only with conditions: use ternary in the initializer instead — skip here
            // (these were already handled by EmitConstructionWithInitializer if no conditions,
            //  or we need to handle conditional init-only differently)
            // For conditional init-only: we can't assign after construction, so skip with a warning
            if (match.IsInitOnly && !match.DestPropertyName.Contains("."))
                continue;

            var assignment = EmitPropertyAssignment(match, typePair.AllowNullCollections);
            bool hasPreCondition = match.PreConditionExpression is not null;
            bool hasCondition = match.ConditionExpression is not null;

            // Handle dotted dest paths (ForPath / unflattening)
            if (match.DestPropertyName.Contains(".") && match.DestPathIntermediateTypes is not null)
            {
                EmitDottedPathAssignment(sb, match, assignment, destVar, initializedPaths);
                continue;
            }

            if (hasPreCondition || hasCondition)
            {
                // Build the combined condition
                string condExpr;
                if (hasPreCondition && hasCondition)
                {
                    condExpr = $"({match.PreConditionExpression}) && ({match.ConditionExpression})";
                }
                else if (hasPreCondition)
                {
                    condExpr = match.PreConditionExpression!;
                }
                else
                {
                    condExpr = match.ConditionExpression!;
                }

                sb.AppendLine($"if ({condExpr})");
                sb.Indent();
                sb.AppendLine($"{destVar}.{match.DestPropertyName} = {assignment};");
                sb.Unindent();
            }
            else
            {
                sb.AppendLine($"{destVar}.{match.DestPropertyName} = {assignment};");
            }
        }
    }

    private static void EmitDottedPathAssignment(
        SourceStringBuilder sb,
        PropertyMatchDescriptor match,
        string assignment,
        string destVar,
        HashSet<string> initializedPaths)
    {
        var pathSegments = match.DestPropertyName.Split('.');
        var intermediateTypes = match.DestPathIntermediateTypes!.Split('|');

        // Emit ??= new for each intermediate segment
        var currentPath = destVar;
        for (int j = 0; j < pathSegments.Length - 1 && j < intermediateTypes.Length; j++)
        {
            currentPath = currentPath + "." + pathSegments[j];
            if (!initializedPaths.Contains(currentPath))
            {
                sb.AppendLine($"{currentPath} ??= new {intermediateTypes[j]}();");
                initializedPaths.Add(currentPath);
            }
        }

        // Emit the leaf assignment
        sb.AppendLine($"{destVar}.{match.DestPropertyName} = {assignment};");
    }

    private static string EmitPropertyAssignment(PropertyMatchDescriptor match, bool allowNullCollections = false)
    {
        // MemberValueResolver takes priority
        if (match.MemberValueResolverTypeName is not null)
        {
            var memberSrcAccess = $"source.{match.SourcePropertyName}";
            var resolverExpr = $"new {match.MemberValueResolverTypeName}().Resolve(source, default!, {memberSrcAccess}, default!, default!)";
            return match.NullSubstituteExpression is not null
                ? $"{resolverExpr} ?? ({match.NullSubstituteExpression})"
                : resolverExpr;
        }

        // ValueResolver takes priority
        if (match.ValueResolverTypeName is not null)
        {
            var resolverExpr = $"new {match.ValueResolverTypeName}().Resolve(source, default!, default!, default!)";
            return match.NullSubstituteExpression is not null
                ? $"{resolverExpr} ?? ({match.NullSubstituteExpression})"
                : resolverExpr;
        }

        var sourceAccess = match.SourcePropertyName.Contains(".")
            ? $"source.{match.SourcePropertyName}"
            : $"source.{match.SourcePropertyName}";

        // NullSubstitute wraps the normal assignment
        if (match.NullSubstituteExpression is not null)
        {
            var baseExpr = EmitConversionExpression(match, sourceAccess, allowNullCollections);
            return $"{baseExpr} ?? ({match.NullSubstituteExpression})";
        }

        return EmitConversionExpression(match, sourceAccess, allowNullCollections);
    }

    private static void EmitMultiSourceMapMethod(SourceStringBuilder sb, TypePairDescriptor typePair)
    {
        var methodName = GetMapMethodName(typePair);
        // Build ValueTuple type args: (PrimarySource, Additional1, Additional2, ...)
        var tupleTypes = new System.Text.StringBuilder();
        tupleTypes.Append(typePair.SourceFullName);
        for (int i = 0; i < typePair.AdditionalSourceTypes.Length; i++)
        {
            tupleTypes.Append(", ");
            tupleTypes.Append(typePair.AdditionalSourceTypes[i]);
        }

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Maps from multiple sources to <see cref=\"{EscapeXmlComment(typePair.DestFullName)}\"/>.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public static {typePair.DestFullName} {methodName}(this ({tupleTypes}) sources)");
        sb.OpenBrace();

        sb.AppendLine($"return sources.Item1.{methodName}();");

        sb.CloseBrace();
    }

    private static bool _emitDeepClone;

    private static string EmitConversionExpression(PropertyMatchDescriptor match, string sourceAccess, bool allowNullCollections = false)
    {
        switch (match.ConversionKind)
        {
            case ConversionKind.Direct:
            case ConversionKind.ImplicitCast:
                // Deep clone: for reference types that are same-typed, recursively clone
                if (_emitDeepClone && !IsValueType(match.SourcePropertyType)
                    && string.Equals(match.SourcePropertyType, match.DestPropertyType, StringComparison.Ordinal))
                {
                    var simpleName = GetSimpleName(match.DestPropertyType);
                    return $"{sourceAccess} is not null ? {sourceAccess}.MapTo{simpleName}() : default";
                }
                return sourceAccess;

            case ConversionKind.ExplicitCast:
                return $"({match.DestPropertyType}){sourceAccess}";

            case ConversionKind.ToString:
                return IsNullableReferenceType(match.SourcePropertyType)
                    ? $"{sourceAccess}?.ToString() ?? string.Empty"
                    : $"{sourceAccess}.ToString()";

            case ConversionKind.Parse:
                return $"({match.DestPropertyType})global::System.Enum.Parse(typeof({match.DestPropertyType}), {sourceAccess})";

            case ConversionKind.EnumByName:
                return EmitEnumByNameSwitch(match, sourceAccess);

            case ConversionKind.EnumByValue:
                return $"({match.DestPropertyType})(int){sourceAccess}";

            case ConversionKind.EnumFlagsByValue:
                return $"({match.DestPropertyType})(int){sourceAccess}";

            case ConversionKind.Nested:
                var destSimpleName = GetSimpleName(match.DestPropertyType);
                return $"{sourceAccess} is not null ? {sourceAccess}.MapTo{destSimpleName}() : default";

            case ConversionKind.Collection:
                return EmitCollectionAssignment(match, sourceAccess, allowNullCollections);

            case ConversionKind.Dictionary:
                return EmitDictionaryAssignment(match, sourceAccess, allowNullCollections);

            case ConversionKind.NullableUnwrap:
                return $"{sourceAccess}.GetValueOrDefault()";

            case ConversionKind.NullableWrap:
                return $"({match.DestPropertyType}){sourceAccess}";

            case ConversionKind.NullableConvert:
                return $"{sourceAccess}.HasValue ? ({match.DestPropertyType}){sourceAccess}.Value : default({match.DestPropertyType})";

            case ConversionKind.DictionaryToObject:
                return EmitDictionaryToObjectAccess(match);

            case ConversionKind.EnumByNameCaseInsensitive:
                return EmitEnumByNameCaseInsensitiveSwitch(match, sourceAccess);

            default:
                return sourceAccess;
        }
    }

    private static string EmitDictionaryToObjectAccess(PropertyMatchDescriptor match)
    {
        var key = match.DestPropertyName;
        return $"source.ContainsKey(\"{key}\") ? ({match.DestPropertyType})source[\"{key}\"] : default({match.DestPropertyType})";
    }

    private static string EmitEnumByNameCaseInsensitiveSwitch(PropertyMatchDescriptor match, string sourceAccess)
    {
        if (match.EnumMembers is null || match.EnumMembers.Value.Length == 0)
        {
            return $"({match.DestPropertyType})global::System.Enum.Parse(typeof({match.DestPropertyType}), {sourceAccess}.ToString())";
        }

        var sb = new System.Text.StringBuilder();
        sb.Append(sourceAccess);
        sb.Append(".ToString().ToUpperInvariant() switch { ");

        foreach (var pair in match.EnumMembers.Value)
        {
            sb.Append($"\"{pair.SourceMemberName.ToUpperInvariant()}\" => {match.DestPropertyType}.{pair.DestMemberName}, ");
        }

        sb.Append($"var __v => ({match.DestPropertyType})global::System.Enum.Parse(typeof({match.DestPropertyType}), __v, true)");
        sb.Append(" }");
        return sb.ToString();
    }

    private static string EmitEnumByNameSwitch(PropertyMatchDescriptor match, string sourceAccess)
    {
        if (match.EnumMembers is null || match.EnumMembers.Value.Length == 0)
        {
            // Fallback to Enum.Parse if no members were resolved
            return $"({match.DestPropertyType})global::System.Enum.Parse(typeof({match.DestPropertyType}), {sourceAccess}.ToString())";
        }

        var sb = new System.Text.StringBuilder();
        sb.Append(sourceAccess);
        sb.Append(" switch { ");

        foreach (var pair in match.EnumMembers.Value)
        {
            sb.Append($"{match.SourcePropertyType}.{pair.SourceMemberName} => {match.DestPropertyType}.{pair.DestMemberName}, ");
        }

        sb.Append($"_ => throw new global::System.InvalidOperationException($\"Cannot map enum value {{{sourceAccess}}} to {match.DestPropertyType}.\")");
        sb.Append(" }");
        return sb.ToString();
    }

    private static string EmitCollectionAssignment(PropertyMatchDescriptor match, string sourceAccess, bool allowNullCollections = false)
    {
        var srcElem = match.SourceElementType;
        var dstElem = match.DestElementType;
        bool sameElement = string.Equals(srcElem, dstElem, StringComparison.Ordinal);

        string selectExpr;
        if (_emitDeepClone && sameElement && dstElem is not null && !IsValueType(dstElem))
        {
            // Deep clone: recursively clone each element even though types are identical
            var dstElemSimple = GetSimpleName(dstElem);
            selectExpr = $"{sourceAccess}.Select(x => x.MapTo{dstElemSimple}())";
        }
        else if (sameElement || srcElem is null || dstElem is null)
        {
            selectExpr = sourceAccess;
        }
        else
        {
            var dstElemSimple = GetSimpleName(dstElem);
            selectExpr = $"{sourceAccess}.Select(x => x.MapTo{dstElemSimple}())";
        }

        string nullFallback;
        if (allowNullCollections)
        {
            nullFallback = "null";
        }
        else
        {
            switch (match.DestCollectionKind)
            {
                case CollectionKind.Array:
                    nullFallback = $"global::System.Array.Empty<{dstElem ?? srcElem}>()";
                    break;
                case CollectionKind.HashSet:
                    nullFallback = $"new global::System.Collections.Generic.HashSet<{dstElem ?? srcElem}>()";
                    break;
                default:
                    nullFallback = $"new global::System.Collections.Generic.List<{dstElem ?? srcElem}>()";
                    break;
            }
        }

        switch (match.DestCollectionKind)
        {
            case CollectionKind.Array:
                return $"{sourceAccess} is not null ? {selectExpr}.ToArray() : {nullFallback}";

            case CollectionKind.HashSet:
                return $"{sourceAccess} is not null ? new global::System.Collections.Generic.HashSet<{dstElem ?? srcElem}>({selectExpr}) : {nullFallback}";

            case CollectionKind.List:
            default:
                return $"{sourceAccess} is not null ? {selectExpr}.ToList() : {nullFallback}";
        }
    }

    private static string EmitDictionaryAssignment(PropertyMatchDescriptor match, string sourceAccess, bool allowNullCollections = false)
    {
        var keyType = match.DictKeyType ?? "object";
        var valType = match.DictValueType ?? "object";
        var nullFallback = allowNullCollections
            ? "null"
            : $"new global::System.Collections.Generic.Dictionary<{keyType}, {valType}>()";
        return $"{sourceAccess} is not null ? new global::System.Collections.Generic.Dictionary<{keyType}, {valType}>({sourceAccess}) : {nullFallback}";
    }

    private static string GetDepthFieldName(TypePairDescriptor typePair)
    {
        var sanitized = SanitizeName(typePair.SourceName) + "To" + SanitizeName(typePair.DestName);
        return $"_depth_{sanitized}";
    }

    private static string SanitizeName(string name)
    {
        return name.Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace(",", "_");
    }

    private static bool IsNullableReferenceType(string typeName)
    {
        return typeName.EndsWith("?", StringComparison.Ordinal);
    }

    private static bool IsValueType(string typeName)
    {
        switch (typeName)
        {
            case "int":
            case "long":
            case "short":
            case "byte":
            case "bool":
            case "char":
            case "float":
            case "double":
            case "decimal":
            case "string":
            case "System.Int32":
            case "System.Int64":
            case "System.Int16":
            case "System.Byte":
            case "System.Boolean":
            case "System.Char":
            case "System.Single":
            case "System.Double":
            case "System.Decimal":
            case "System.DateTime":
            case "System.DateTimeOffset":
            case "System.TimeSpan":
            case "System.Guid":
            case "System.String":
                return true;
            default:
                return false;
        }
    }

    private static string GetSimpleName(string fullName)
    {
        var lastDot = fullName.LastIndexOf('.');
        return lastDot >= 0 ? fullName.Substring(lastDot + 1) : fullName;
    }

    private static string GetNamespace(string fullName)
    {
        var lastDot = fullName.LastIndexOf('.');
        return lastDot >= 0 ? fullName.Substring(0, lastDot) : string.Empty;
    }

    private static string EscapeXmlComment(string text)
    {
        return text.Replace("<", "{").Replace(">", "}");
    }
}
