using System;
using System.Collections.Generic;
using System.Linq;
using OpenAutoMapper.Generator.Helpers;
using OpenAutoMapper.Generator.Models;

namespace OpenAutoMapper.Generator.Pipeline;

/// <summary>
/// Stage 3b: Emits the IMapper implementation and factory initializer.
/// </summary>
internal static class MapperImplEmitter
{
    /// <summary>
    /// Generates the OpenAutoMapperImpl class that implements IMapper with
    /// a type-switch dispatch for all discovered mappings.
    /// </summary>
    public static string EmitMapperImplementation(List<TypePairDescriptor> allTypePairs)
    {
        // Sort type pairs so derived types appear before their base types in if-chains.
        var sorted = SortDerivedBeforeBase(allTypePairs);

        var sb = new SourceStringBuilder();

        var needsCollections = sorted.Any(tp => tp.PropertyMatches.Any(m => m.ConversionKind == ConversionKind.Collection));
        var needsDictionary = sorted.Any(tp => tp.PropertyMatches.Any(m => m.ConversionKind == ConversionKind.Dictionary));

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        if (needsCollections || needsDictionary)
        {
            sb.AppendLine("using System.Collections.Generic;");
        }
        if (needsCollections)
        {
            sb.AppendLine("using System.Linq;");
        }

        // Add using directives for namespaces where extension methods are generated
        var extensionNamespaces = new HashSet<string>(StringComparer.Ordinal);
        foreach (var pair in sorted)
        {
            var ns = GetNamespace(pair.DestFullName);
            if (!string.IsNullOrEmpty(ns) && !string.Equals(ns, "OpenAutoMapper.Generated", StringComparison.Ordinal))
            {
                extensionNamespaces.Add(ns);
            }
        }

        foreach (var ns in extensionNamespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace OpenAutoMapper.Generated;");
        sb.AppendLine();
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"OpenAutoMapper.Generator\", \"1.0.0.0\")]");
        sb.AppendLine("internal sealed class OpenAutoMapperImpl : global::OpenAutoMapper.IMapper");
        sb.OpenBrace();

        // Map<TDest>(object source) -- single generic parameter
        EmitMapSingleGeneric(sb, sorted);
        sb.AppendLine();

        // Map<TSource, TDest>(TSource source) -- two generic parameters, new instance
        EmitMapTwoGeneric(sb, sorted);
        sb.AppendLine();

        // Map<TSource, TDest>(TSource source, TDest destination) -- update existing
        EmitMapTwoGenericUpdate(sb, sorted);
        sb.AppendLine();

        // Map(object source, Type sourceType, Type destinationType) -- non-generic
        EmitMapNonGeneric(sb, sorted);
        sb.AppendLine();

        // Map(object source, object destination, Type sourceType, Type destinationType) -- non-generic update
        EmitMapNonGenericUpdate(sb, sorted);
        sb.AppendLine();

        // Map<TSource, TDest>(TSource source, string mappingName) -- named mapping dispatch
        EmitMapNamedGeneric(sb, sorted);

        sb.CloseBrace();

        return sb.ToString();
    }

    /// <summary>
    /// Generates the factory initializer that hooks into MapperConfiguration.MapperFactory.
    /// </summary>
    public static string EmitFactoryInitializer()
    {
        var sb = new SourceStringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace OpenAutoMapper.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Module initializer that registers the source-generated mapper factory.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"OpenAutoMapper.Generator\", \"1.0.0.0\")]");
        sb.AppendLine("internal static class OpenAutoMapperFactoryInit");
        sb.OpenBrace();

        sb.AppendLine("[ModuleInitializer]");
        sb.AppendLine("internal static void Initialize()");
        sb.OpenBrace();
        sb.AppendLine("// Register the generated mapper factory so that MapperConfiguration.CreateMapper() works.");
        sb.AppendLine("// Uses reflection to set the internal static property since the generator cannot reference Core directly.");
        sb.AppendLine("var configType = typeof(global::OpenAutoMapper.MapperConfiguration);");
        sb.AppendLine("var factoryProperty = configType.GetProperty(\"MapperFactory\",");
        sb.Indent();
        sb.AppendLine("System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);");
        sb.Unindent();
        sb.AppendLine("if (factoryProperty is not null)");
        sb.OpenBrace();
        sb.AppendLine("factoryProperty.SetValue(null, new global::System.Func<global::OpenAutoMapper.MapperConfiguration, global::OpenAutoMapper.IMapper>(");
        sb.Indent();
        sb.AppendLine("config => new OpenAutoMapperImpl()));");
        sb.Unindent();
        sb.CloseBrace();

        sb.CloseBrace();

        sb.CloseBrace();

        return sb.ToString();
    }

    /// <summary>
    /// Sort type pairs so derived types come before their base types in dispatch chains.
    /// This ensures "if (source is Dog ...)" is checked before "if (source is Animal ...)".
    /// </summary>
    private static List<TypePairDescriptor> SortDerivedBeforeBase(List<TypePairDescriptor> typePairs)
    {
        // Collect all derived->base relationships
        var derivedSources = new HashSet<string>(StringComparer.Ordinal);
        foreach (var tp in typePairs)
        {
            foreach (var derived in tp.IncludedDerivedTypes)
            {
                derivedSources.Add(derived.SourceFullName);
            }
        }

        // Derived types first, then base types, then others (preserve relative order)
        var derivedPairs = new List<TypePairDescriptor>();
        var basePairs = new List<TypePairDescriptor>();
        var otherPairs = new List<TypePairDescriptor>();

        foreach (var tp in typePairs)
        {
            if (derivedSources.Contains(tp.SourceFullName))
                derivedPairs.Add(tp);
            else if (tp.IsPolymorphicBase)
                basePairs.Add(tp);
            else
                otherPairs.Add(tp);
        }

        var result = new List<TypePairDescriptor>(typePairs.Count);
        result.AddRange(derivedPairs);
        result.AddRange(otherPairs);
        result.AddRange(basePairs);
        return result;
    }

    private static void EmitMapSingleGeneric(SourceStringBuilder sb, List<TypePairDescriptor> typePairs)
    {
        sb.AppendLine("public TDestination Map<TDestination>(object source)");
        sb.OpenBrace();

        sb.AppendLine("if (source is null)");
        sb.Indent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(source));");
        sb.Unindent();
        sb.AppendLine();

        foreach (var pair in typePairs)
        {
            // Skip named mappings in default dispatch
            if (pair.MappingName is not null)
                continue;

            var methodName = MappingCodeEmitter.GetMapMethodName(pair);
            sb.AppendLine($"if (source is {pair.SourceFullName} src_{SanitizeName(pair.SourceName)} && typeof(TDestination) == typeof({pair.DestFullName}))");
            sb.Indent();
            sb.AppendLine($"return (TDestination)(object)src_{SanitizeName(pair.SourceName)}.{methodName}();");
            sb.Unindent();
        }

        sb.AppendLine();
        sb.AppendLine("throw new global::System.InvalidOperationException(");
        sb.Indent();
        sb.AppendLine("$\"No mapping configured from {source.GetType().FullName} to {typeof(TDestination).FullName}.\");");
        sb.Unindent();

        sb.CloseBrace();
    }

    private static void EmitMapTwoGeneric(SourceStringBuilder sb, List<TypePairDescriptor> typePairs)
    {
        sb.AppendLine("public TDestination Map<TSource, TDestination>(TSource source)");
        sb.OpenBrace();

        sb.AppendLine("if (source is null)");
        sb.Indent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(source));");
        sb.Unindent();
        sb.AppendLine();

        foreach (var pair in typePairs)
        {
            if (pair.MappingName is not null)
                continue;

            var methodName = MappingCodeEmitter.GetMapMethodName(pair);
            sb.AppendLine($"if (source is {pair.SourceFullName} src_{SanitizeName(pair.SourceName)} && typeof(TDestination) == typeof({pair.DestFullName}))");
            sb.Indent();
            sb.AppendLine($"return (TDestination)(object)src_{SanitizeName(pair.SourceName)}.{methodName}();");
            sb.Unindent();
        }

        sb.AppendLine();
        sb.AppendLine("throw new global::System.InvalidOperationException(");
        sb.Indent();
        sb.AppendLine("$\"No mapping configured from {typeof(TSource).FullName} to {typeof(TDestination).FullName}.\");");
        sb.Unindent();

        sb.CloseBrace();
    }

    private static void EmitMapTwoGenericUpdate(SourceStringBuilder sb, List<TypePairDescriptor> typePairs)
    {
        sb.AppendLine("public TDestination Map<TSource, TDestination>(TSource source, TDestination destination)");
        sb.OpenBrace();

        sb.AppendLine("if (source is null)");
        sb.Indent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(source));");
        sb.Unindent();
        sb.AppendLine("if (destination is null)");
        sb.Indent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(destination));");
        sb.Unindent();
        sb.AppendLine();

        foreach (var pair in typePairs)
        {
            if (pair.MappingName is not null)
                continue;
            sb.AppendLine($"if (source is {pair.SourceFullName} src_{SanitizeName(pair.SourceName)} && destination is {pair.DestFullName} dest_{SanitizeName(pair.DestName)})");
            sb.OpenBrace();

            var srcVar = $"src_{SanitizeName(pair.SourceName)}";
            var dstVar = $"dest_{SanitizeName(pair.DestName)}";

            if (pair.BeforeMapExpression is not null)
            {
                sb.AppendLine($"((global::System.Action<{pair.SourceFullName}, {pair.DestFullName}>)({pair.BeforeMapExpression}))({srcVar}, {dstVar});");
            }

            EmitUpdatePropertyAssignments(sb, pair, srcVar, dstVar);

            if (pair.AfterMapExpression is not null)
            {
                sb.AppendLine($"((global::System.Action<{pair.SourceFullName}, {pair.DestFullName}>)({pair.AfterMapExpression}))({srcVar}, {dstVar});");
            }

            sb.AppendLine($"return (TDestination)(object){dstVar};");
            sb.CloseBrace();
        }

        sb.AppendLine();
        sb.AppendLine("throw new global::System.InvalidOperationException(");
        sb.Indent();
        sb.AppendLine("$\"No mapping configured from {typeof(TSource).FullName} to {typeof(TDestination).FullName}.\");");
        sb.Unindent();

        sb.CloseBrace();
    }

    private static void EmitMapNonGeneric(SourceStringBuilder sb, List<TypePairDescriptor> typePairs)
    {
        sb.AppendLine("public object Map(object source, global::System.Type sourceType, global::System.Type destinationType)");
        sb.OpenBrace();

        sb.AppendLine("if (source is null)");
        sb.Indent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(source));");
        sb.Unindent();
        sb.AppendLine();

        foreach (var pair in typePairs)
        {
            if (pair.MappingName is not null)
                continue;

            var methodName = MappingCodeEmitter.GetMapMethodName(pair);
            sb.AppendLine($"if (source is {pair.SourceFullName} src_{SanitizeName(pair.SourceName)} && destinationType == typeof({pair.DestFullName}))");
            sb.Indent();
            sb.AppendLine($"return src_{SanitizeName(pair.SourceName)}.{methodName}();");
            sb.Unindent();
        }

        sb.AppendLine();
        sb.AppendLine("throw new global::System.InvalidOperationException(");
        sb.Indent();
        sb.AppendLine("$\"No mapping configured from {sourceType.FullName} to {destinationType.FullName}.\");");
        sb.Unindent();

        sb.CloseBrace();
    }

    private static void EmitMapNonGenericUpdate(SourceStringBuilder sb, List<TypePairDescriptor> typePairs)
    {
        sb.AppendLine("public object Map(object source, object destination, global::System.Type sourceType, global::System.Type destinationType)");
        sb.OpenBrace();

        sb.AppendLine("if (source is null)");
        sb.Indent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(source));");
        sb.Unindent();
        sb.AppendLine("if (destination is null)");
        sb.Indent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(destination));");
        sb.Unindent();
        sb.AppendLine();

        foreach (var pair in typePairs)
        {
            if (pair.MappingName is not null)
                continue;
            sb.AppendLine($"if (source is {pair.SourceFullName} src_{SanitizeName(pair.SourceName)} && destination is {pair.DestFullName} dest_{SanitizeName(pair.DestName)})");
            sb.OpenBrace();

            var srcVar = $"src_{SanitizeName(pair.SourceName)}";
            var dstVar = $"dest_{SanitizeName(pair.DestName)}";

            if (pair.BeforeMapExpression is not null)
            {
                sb.AppendLine($"((global::System.Action<{pair.SourceFullName}, {pair.DestFullName}>)({pair.BeforeMapExpression}))({srcVar}, {dstVar});");
            }

            EmitUpdatePropertyAssignments(sb, pair, srcVar, dstVar);

            if (pair.AfterMapExpression is not null)
            {
                sb.AppendLine($"((global::System.Action<{pair.SourceFullName}, {pair.DestFullName}>)({pair.AfterMapExpression}))({srcVar}, {dstVar});");
            }

            sb.AppendLine($"return {dstVar};");
            sb.CloseBrace();
        }

        sb.AppendLine();
        sb.AppendLine("throw new global::System.InvalidOperationException(");
        sb.Indent();
        sb.AppendLine("$\"No mapping configured from {sourceType.FullName} to {destinationType.FullName}.\");");
        sb.Unindent();

        sb.CloseBrace();
    }

    private static void EmitMapNamedGeneric(SourceStringBuilder sb, List<TypePairDescriptor> typePairs)
    {
        sb.AppendLine("public TDestination Map<TSource, TDestination>(TSource source, string mappingName)");
        sb.OpenBrace();

        sb.AppendLine("if (source is null)");
        sb.Indent();
        sb.AppendLine("throw new global::System.ArgumentNullException(nameof(source));");
        sb.Unindent();
        sb.AppendLine();

        bool hasNamedMappings = false;
        foreach (var pair in typePairs)
        {
            if (pair.MappingName is null)
                continue;
            hasNamedMappings = true;

            var methodName = MappingCodeEmitter.GetMapMethodName(pair);
            sb.AppendLine($"if (source is {pair.SourceFullName} src_{SanitizeName(pair.SourceName)}_{SanitizeName(pair.MappingName)} && typeof(TDestination) == typeof({pair.DestFullName}) && string.Equals(mappingName, \"{pair.MappingName}\", global::System.StringComparison.Ordinal))");
            sb.Indent();
            sb.AppendLine($"return (TDestination)(object)src_{SanitizeName(pair.SourceName)}_{SanitizeName(pair.MappingName)}.{methodName}();");
            sb.Unindent();
        }

        if (!hasNamedMappings)
        {
            sb.AppendLine("// No named mappings configured");
        }

        sb.AppendLine();
        sb.AppendLine("throw new global::System.InvalidOperationException(");
        sb.Indent();
        sb.AppendLine("$\"No named mapping '{mappingName}' configured from {typeof(TSource).FullName} to {typeof(TDestination).FullName}.\");");
        sb.Unindent();

        sb.CloseBrace();
    }

    private static void EmitUpdatePropertyAssignments(
        SourceStringBuilder sb,
        TypePairDescriptor pair,
        string srcVar,
        string dstVar)
    {
        var initializedPaths = new HashSet<string>(StringComparer.Ordinal);

        foreach (var match in pair.PropertyMatches)
        {
            // Skip init-only properties in update methods (can't re-set after construction)
            if (match.IsInitOnly)
                continue;

            var assignment = EmitInlineAssignment(match, srcVar);
            bool hasPreCondition = match.PreConditionExpression is not null;
            bool hasCondition = match.ConditionExpression is not null;

            // Handle dotted dest paths (ForPath / unflattening)
            if (match.DestPropertyName.Contains(".") && match.DestPathIntermediateTypes is not null)
            {
                var pathSegments = match.DestPropertyName.Split('.');
                var intermediateTypes = match.DestPathIntermediateTypes.Split('|');

                var currentPath = dstVar;
                for (int j = 0; j < pathSegments.Length - 1 && j < intermediateTypes.Length; j++)
                {
                    currentPath = currentPath + "." + pathSegments[j];
                    if (!initializedPaths.Contains(currentPath))
                    {
                        sb.AppendLine($"{currentPath} ??= new {intermediateTypes[j]}();");
                        initializedPaths.Add(currentPath);
                    }
                }

                sb.AppendLine($"{dstVar}.{match.DestPropertyName} = {assignment};");
                continue;
            }

            if (hasPreCondition || hasCondition)
            {
                string condExpr;
                if (hasPreCondition && hasCondition)
                    condExpr = $"({match.PreConditionExpression}) && ({match.ConditionExpression})";
                else if (hasPreCondition)
                    condExpr = match.PreConditionExpression!;
                else
                    condExpr = match.ConditionExpression!;

                sb.AppendLine($"if ({condExpr})");
                sb.Indent();
                sb.AppendLine($"{dstVar}.{match.DestPropertyName} = {assignment};");
                sb.Unindent();
            }
            else
            {
                sb.AppendLine($"{dstVar}.{match.DestPropertyName} = {assignment};");
            }
        }
    }

    private static string EmitInlineAssignment(PropertyMatchDescriptor match, string sourceVarName)
    {
        // DictionaryToObject: use dictionary key access
        if (match.ConversionKind == ConversionKind.DictionaryToObject)
        {
            return $"{sourceVarName}.ContainsKey(\"{match.DestPropertyName}\") ? ({match.DestPropertyType}){sourceVarName}[\"{match.DestPropertyName}\"] : default({match.DestPropertyType})";
        }

        // MemberValueResolver takes priority
        if (match.MemberValueResolverTypeName is not null)
        {
            var memberSrcAccess = $"{sourceVarName}.{match.SourcePropertyName}";
            var resolverExpr = $"new {match.MemberValueResolverTypeName}().Resolve({sourceVarName}, default!, {memberSrcAccess}, default!, default!)";
            return match.NullSubstituteExpression is not null
                ? $"{resolverExpr} ?? ({match.NullSubstituteExpression})"
                : resolverExpr;
        }

        // ValueResolver takes priority
        if (match.ValueResolverTypeName is not null)
        {
            var resolverExpr = $"new {match.ValueResolverTypeName}().Resolve({sourceVarName}, default!, default!, default!)";
            return match.NullSubstituteExpression is not null
                ? $"{resolverExpr} ?? ({match.NullSubstituteExpression})"
                : resolverExpr;
        }

        var sourceAccess = match.SourcePropertyName.Contains(".")
            ? $"{sourceVarName}.{match.SourcePropertyName}"
            : $"{sourceVarName}.{match.SourcePropertyName}";

        if (match.NullSubstituteExpression is not null)
        {
            var baseExpr = EmitInlineConversion(match, sourceAccess);
            return $"{baseExpr} ?? ({match.NullSubstituteExpression})";
        }

        return EmitInlineConversion(match, sourceAccess);
    }

    private static string EmitInlineConversion(PropertyMatchDescriptor match, string sourceAccess)
    {
        switch (match.ConversionKind)
        {
            case ConversionKind.Direct:
            case ConversionKind.ImplicitCast:
                return sourceAccess;

            case ConversionKind.ExplicitCast:
                return $"({match.DestPropertyType}){sourceAccess}";

            case ConversionKind.ToString:
                return $"{sourceAccess}.ToString()";

            case ConversionKind.Parse:
                return $"({match.DestPropertyType})global::System.Enum.Parse(typeof({match.DestPropertyType}), {sourceAccess})";

            case ConversionKind.EnumByName:
                return EmitEnumByNameSwitchInline(match, sourceAccess);

            case ConversionKind.EnumByValue:
                return $"({match.DestPropertyType})(int){sourceAccess}";

            case ConversionKind.EnumFlagsByValue:
                return $"({match.DestPropertyType})(int){sourceAccess}";

            case ConversionKind.Nested:
                var destSimpleName = GetSimpleName(match.DestPropertyType);
                return $"{sourceAccess}?.MapTo{destSimpleName}()";

            case ConversionKind.Collection:
                return EmitCollectionInlineAssignment(match, sourceAccess, false);

            case ConversionKind.Dictionary:
                return EmitDictionaryInlineAssignment(match, sourceAccess, false);

            case ConversionKind.NullableUnwrap:
                return $"{sourceAccess}.GetValueOrDefault()";

            case ConversionKind.NullableWrap:
                return $"({match.DestPropertyType}){sourceAccess}";

            case ConversionKind.NullableConvert:
                return $"{sourceAccess}.HasValue ? ({match.DestPropertyType}){sourceAccess}.Value : default({match.DestPropertyType})";

            case ConversionKind.DictionaryToObject:
                return sourceAccess; // handled in EmitInlineAssignment

            case ConversionKind.EnumByNameCaseInsensitive:
                return EmitEnumByNameCaseInsensitiveSwitchInline(match, sourceAccess);

            default:
                return sourceAccess;
        }
    }

    private static string EmitEnumByNameCaseInsensitiveSwitchInline(PropertyMatchDescriptor match, string sourceAccess)
    {
        if (match.EnumMembers is null || match.EnumMembers.Value.Length == 0)
        {
            return $"({match.DestPropertyType})global::System.Enum.Parse(typeof({match.DestPropertyType}), {sourceAccess}.ToString())";
        }

        var sb = new System.Text.StringBuilder();
        sb.Append(sourceAccess);
        sb.Append(".ToString().ToUpperInvariant() switch { ");

        foreach (var pair in match.EnumMembers.Value)
        {
            sb.Append($"\"{pair.SourceMemberName.ToUpperInvariant()}\" => {match.DestPropertyType}.{pair.DestMemberName}, ");
        }

        sb.Append($"var __v => ({match.DestPropertyType})global::System.Enum.Parse(typeof({match.DestPropertyType}), __v, true)");
        sb.Append(" }");
        return sb.ToString();
    }

    private static string EmitEnumByNameSwitchInline(PropertyMatchDescriptor match, string sourceAccess)
    {
        if (match.EnumMembers is null || match.EnumMembers.Value.Length == 0)
        {
            return $"({match.DestPropertyType})global::System.Enum.Parse(typeof({match.DestPropertyType}), {sourceAccess}.ToString())";
        }

        var sb = new System.Text.StringBuilder();
        sb.Append(sourceAccess);
        sb.Append(" switch { ");

        foreach (var pair in match.EnumMembers.Value)
        {
            sb.Append($"{match.SourcePropertyType}.{pair.SourceMemberName} => {match.DestPropertyType}.{pair.DestMemberName}, ");
        }

        sb.Append($"_ => throw new global::System.InvalidOperationException($\"Cannot map enum value {{{sourceAccess}}} to {match.DestPropertyType}.\")");
        sb.Append(" }");
        return sb.ToString();
    }

    private static string EmitCollectionInlineAssignment(PropertyMatchDescriptor match, string sourceAccess, bool allowNullCollections)
    {
        var srcElem = match.SourceElementType;
        var dstElem = match.DestElementType;
        bool sameElement = string.Equals(srcElem, dstElem, StringComparison.Ordinal);

        string selectExpr;
        if (sameElement || srcElem is null || dstElem is null)
        {
            selectExpr = sourceAccess;
        }
        else
        {
            var dstElemSimple = GetSimpleName(dstElem);
            selectExpr = $"{sourceAccess}.Select(x => x.MapTo{dstElemSimple}())";
        }

        string nullFallback;
        if (allowNullCollections)
        {
            nullFallback = "null";
        }
        else
        {
            switch (match.DestCollectionKind)
            {
                case CollectionKind.Array:
                    nullFallback = $"global::System.Array.Empty<{dstElem ?? srcElem}>()";
                    break;
                case CollectionKind.HashSet:
                    nullFallback = $"new global::System.Collections.Generic.HashSet<{dstElem ?? srcElem}>()";
                    break;
                default:
                    nullFallback = $"new global::System.Collections.Generic.List<{dstElem ?? srcElem}>()";
                    break;
            }
        }

        switch (match.DestCollectionKind)
        {
            case CollectionKind.Array:
                return $"{sourceAccess} is not null ? {selectExpr}.ToArray() : {nullFallback}";

            case CollectionKind.HashSet:
                return $"{sourceAccess} is not null ? new global::System.Collections.Generic.HashSet<{dstElem ?? srcElem}>({selectExpr}) : {nullFallback}";

            case CollectionKind.List:
            default:
                return $"{sourceAccess} is not null ? {selectExpr}.ToList() : {nullFallback}";
        }
    }

    private static string EmitDictionaryInlineAssignment(PropertyMatchDescriptor match, string sourceAccess, bool allowNullCollections)
    {
        var keyType = match.DictKeyType ?? "object";
        var valType = match.DictValueType ?? "object";
        var nullFallback = allowNullCollections
            ? "null"
            : $"new global::System.Collections.Generic.Dictionary<{keyType}, {valType}>()";
        return $"{sourceAccess} is not null ? new global::System.Collections.Generic.Dictionary<{keyType}, {valType}>({sourceAccess}) : {nullFallback}";
    }

    private static string SanitizeName(string name)
    {
        // Replace any characters that would be invalid in C# identifiers
        return name.Replace(".", "_").Replace("<", "_").Replace(">", "_").Replace(",", "_");
    }

    private static string GetSimpleName(string fullName)
    {
        var lastDot = fullName.LastIndexOf('.');
        return lastDot >= 0 ? fullName.Substring(lastDot + 1) : fullName;
    }

    private static string GetNamespace(string fullName)
    {
        var lastDot = fullName.LastIndexOf('.');
        return lastDot >= 0 ? fullName.Substring(0, lastDot) : string.Empty;
    }
}
