using System;
using System.Collections.Generic;
using System.Linq;
using OpenAutoMapper.Generator.Helpers;
using OpenAutoMapper.Generator.Models;

namespace OpenAutoMapper.Generator.Pipeline;

/// <summary>
/// Emits the generic ProjectTo&lt;TDest&gt;() dispatch method
/// that routes IQueryable to the correct Expression via type checks.
/// </summary>
internal static class ProjectToRegistryEmitter
{
    public static string EmitProjectToDispatch(List<TypePairDescriptor> projectionPairs)
    {
        var sb = new SourceStringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Linq.Expressions;");

        // Add using directives for namespaces where projection expression classes are generated
        var extensionNamespaces = new HashSet<string>(StringComparer.Ordinal);
        foreach (var pair in projectionPairs)
        {
            var ns = GetNamespace(pair.DestFullName);
            if (!string.IsNullOrEmpty(ns) && !string.Equals(ns, "OpenAutoMapper.Generated", StringComparison.Ordinal))
            {
                extensionNamespaces.Add(ns);
            }
        }

        foreach (var ns in extensionNamespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace OpenAutoMapper.Generated;");
        sb.AppendLine();
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"OpenAutoMapper.Generator\", \"1.0.0.0\")]");
        sb.AppendLine("internal static class OpenAutoMapperQueryableExtensions");
        sb.OpenBrace();

        sb.AppendLine("public static IQueryable<TDest> ProjectTo<TDest>(");
        sb.Indent();
        sb.AppendLine("this IQueryable source,");
        sb.AppendLine("global::OpenAutoMapper.IConfigurationProvider? configuration = null)");
        sb.Unindent();
        sb.OpenBrace();

        sb.AppendLine("var elementType = source.ElementType;");
        sb.AppendLine();

        foreach (var pair in projectionPairs)
        {
            var exprClassName = $"{pair.SourceName}To{pair.DestName}ProjectionExpressions";
            var exprClassFullName = GetNamespace(pair.DestFullName) is string ns && !string.IsNullOrEmpty(ns)
                ? $"{ns}.{exprClassName}"
                : exprClassName;

            sb.AppendLine($"if (elementType == typeof({pair.SourceFullName}) && typeof(TDest) == typeof({pair.DestFullName}))");
            sb.Indent();
            sb.AppendLine($"return (IQueryable<TDest>)(object)((IQueryable<{pair.SourceFullName}>)source)");
            sb.Indent();
            sb.AppendLine($".Select({exprClassFullName}.Expression);");
            sb.Unindent();
            sb.Unindent();
            sb.AppendLine();
        }

        sb.AppendLine("throw new global::System.InvalidOperationException(");
        sb.Indent();
        sb.AppendLine("$\"No projection from {elementType.FullName} to {typeof(TDest).FullName}.\");");
        sb.Unindent();

        sb.CloseBrace();

        sb.CloseBrace();

        return sb.ToString();
    }

    private static string GetNamespace(string fullName)
    {
        var lastDot = fullName.LastIndexOf('.');
        return lastDot >= 0 ? fullName.Substring(0, lastDot) : string.Empty;
    }
}
