using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using OpenAutoMapper.Generator.Diagnostics;
using OpenAutoMapper.Generator.Helpers;
using OpenAutoMapper.Generator.Models;

namespace OpenAutoMapper.Generator.Pipeline;

/// <summary>
/// Emits Expression&lt;Func&lt;S,D&gt;&gt; fields and typed ProjectTo extension methods
/// for CreateProjection type pairs.
/// </summary>
internal static class ProjectionExpressionEmitter
{
    /// <summary>
    /// Emits one source file containing:
    /// 1) A static class with Expression&lt;Func&lt;S,D&gt;&gt; field
    /// 2) A typed ProjectTo{Dest} extension on IQueryable&lt;Source&gt;
    /// </summary>
    public static string? EmitProjectionExpression(
        TypePairDescriptor typePair,
        List<TypePairDescriptor> allProjectionPairs,
        SourceProductionContext context)
    {
        if (typePair.PropertyMatches.Length == 0)
            return null;

        // Report OM1042 for dictionary properties and skip them
        var validMatches = new List<PropertyMatchDescriptor>();
        foreach (var match in typePair.PropertyMatches)
        {
            if (match.ConversionKind == ConversionKind.Dictionary)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.DictionaryPropertyInProjection,
                    Location.None,
                    match.DestPropertyName,
                    typePair.SourceFullName,
                    typePair.DestFullName));
                continue;
            }
            validMatches.Add(match);
        }

        if (validMatches.Count == 0)
            return null;

        var sb = new SourceStringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine();

        var destNamespace = GetNamespace(typePair.DestFullName);
        var hasNamespace = !string.IsNullOrEmpty(destNamespace);

        if (hasNamespace)
        {
            sb.AppendLine($"namespace {destNamespace};");
            sb.AppendLine();
        }

        var className = $"{typePair.SourceName}To{typePair.DestName}ProjectionExpressions";

        // Expression class
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"OpenAutoMapper.Generator\", \"1.0.0.0\")]");
        sb.AppendLine($"internal static class {className}");
        sb.OpenBrace();

        sb.AppendLine($"internal static readonly Expression<Func<{typePair.SourceFullName}, {typePair.DestFullName}>> Expression =");
        sb.Indent();
        sb.AppendLine($"source => new {typePair.DestFullName}");
        sb.AppendLine("{");
        sb.Indent();

        // Separate flat and dotted (ForPath/unflatten) matches
        var flatMatches = new List<PropertyMatchDescriptor>();
        var dottedMatches = new List<PropertyMatchDescriptor>();
        foreach (var m in validMatches)
        {
            if (m.DestPropertyName.Contains(".") && m.DestPathIntermediateTypes is not null)
                dottedMatches.Add(m);
            else
                flatMatches.Add(m);
        }

        // Group dotted matches by first path segment
        var dottedGroups = new Dictionary<string, List<PropertyMatchDescriptor>>(StringComparer.Ordinal);
        foreach (var m in dottedMatches)
        {
            var dotIdx = m.DestPropertyName.IndexOf('.');
            var firstSegment = m.DestPropertyName.Substring(0, dotIdx);
            if (!dottedGroups.TryGetValue(firstSegment, out var group))
            {
                group = new List<PropertyMatchDescriptor>();
                dottedGroups[firstSegment] = group;
            }
            group.Add(m);
        }

        int totalItems = flatMatches.Count + dottedGroups.Count;
        int itemIndex = 0;

        // Emit flat matches
        foreach (var match in flatMatches)
        {
            itemIndex++;
            var comma = itemIndex < totalItems ? "," : "";
            var assignment = EmitProjectionAssignment(match, "source", allProjectionPairs);
            sb.AppendLine($"{match.DestPropertyName} = {assignment}{comma}");
        }

        // Emit dotted groups as nested member initializers
        foreach (var kvp in dottedGroups)
        {
            itemIndex++;
            var comma = itemIndex < totalItems ? "," : "";
            var firstSegment = kvp.Key;
            var group = kvp.Value;
            var intermediateType = group[0].DestPathIntermediateTypes!.Split('|')[0];

            sb.AppendLine($"{firstSegment} = new {intermediateType}");
            sb.AppendLine("{");
            sb.Indent();

            for (int j = 0; j < group.Count; j++)
            {
                var m = group[j];
                var innerComma = j < group.Count - 1 ? "," : "";
                // Extract leaf property name from dotted path
                var leafDotIdx = m.DestPropertyName.LastIndexOf('.');
                var leafName = m.DestPropertyName.Substring(leafDotIdx + 1);
                var innerAssignment = EmitProjectionAssignment(m, "source", allProjectionPairs);
                sb.AppendLine($"{leafName} = {innerAssignment}{innerComma}");
            }

            sb.Unindent();
            sb.AppendLine($"}}{comma}");
        }

        sb.Unindent();
        sb.AppendLine("};");
        sb.Unindent();

        sb.CloseBrace();
        sb.AppendLine();

        // Typed extension method
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"OpenAutoMapper.Generator\", \"1.0.0.0\")]");
        sb.AppendLine($"internal static class {typePair.SourceName}To{typePair.DestName}ProjectionExtensions");
        sb.OpenBrace();

        sb.AppendLine($"internal static IQueryable<{typePair.DestFullName}> ProjectTo{typePair.DestName}(this IQueryable<{typePair.SourceFullName}> source)");
        sb.OpenBrace();
        sb.AppendLine($"return source.Select({className}.Expression);");
        sb.CloseBrace();

        sb.CloseBrace();

        return sb.ToString();
    }

    private static string EmitProjectionAssignment(
        PropertyMatchDescriptor match,
        string sourceParam,
        List<TypePairDescriptor> allProjectionPairs)
    {
        var sourceAccess = match.SourcePropertyName.Contains(".")
            ? $"{sourceParam}.{match.SourcePropertyName}"
            : $"{sourceParam}.{match.SourcePropertyName}";

        switch (match.ConversionKind)
        {
            case ConversionKind.Direct:
            case ConversionKind.ImplicitCast:
                return sourceAccess;

            case ConversionKind.ExplicitCast:
                return $"({match.DestPropertyType}){sourceAccess}";

            case ConversionKind.ToString:
                return $"{sourceAccess}.ToString()";

            case ConversionKind.Parse:
                // EF handles string->enum natively
                return sourceAccess;

            case ConversionKind.EnumByName:
            case ConversionKind.EnumByValue:
            case ConversionKind.EnumFlagsByValue:
                return $"({match.DestPropertyType})(int){sourceAccess}";

            case ConversionKind.Nested:
                return EmitNestedProjection(match, sourceAccess, allProjectionPairs);

            case ConversionKind.Collection:
                return EmitCollectionProjection(match, sourceAccess, allProjectionPairs);

            case ConversionKind.NullableUnwrap:
                return $"{sourceAccess}.HasValue ? {sourceAccess}.Value : default";

            case ConversionKind.NullableWrap:
                return sourceAccess;

            case ConversionKind.NullableConvert:
                return $"{sourceAccess}.HasValue ? ({match.DestPropertyType}){sourceAccess}.Value : default({match.DestPropertyType})";

            default:
                return sourceAccess;
        }
    }

    private static string EmitNestedProjection(
        PropertyMatchDescriptor match,
        string sourceAccess,
        List<TypePairDescriptor> allProjectionPairs)
    {
        // Look for a projection pair that maps the nested types
        var nestedPair = allProjectionPairs.FirstOrDefault(p =>
            string.Equals(p.SourceFullName, match.SourcePropertyType, StringComparison.Ordinal) &&
            string.Equals(p.DestFullName, match.DestPropertyType, StringComparison.Ordinal));

        if (nestedPair is not null && nestedPair.PropertyMatches.Length > 0)
        {
            // Inline the member initializer
            var initParts = new List<string>();
            foreach (var prop in nestedPair.PropertyMatches)
            {
                if (prop.ConversionKind == ConversionKind.Dictionary)
                    continue;
                var innerAssignment = EmitProjectionAssignment(prop, sourceAccess, allProjectionPairs);
                initParts.Add($"{prop.DestPropertyName} = {innerAssignment}");
            }
            var initBody = string.Join(", ", initParts);
            return $"{sourceAccess} != null ? new {match.DestPropertyType} {{ {initBody} }} : null";
        }

        // No projection pair found — emit a direct null-safe inline
        return $"{sourceAccess} != null ? new {match.DestPropertyType}() : null";
    }

    private static string EmitCollectionProjection(
        PropertyMatchDescriptor match,
        string sourceAccess,
        List<TypePairDescriptor> allProjectionPairs)
    {
        var srcElem = match.SourceElementType;
        var dstElem = match.DestElementType;
        bool sameElement = string.Equals(srcElem, dstElem, StringComparison.Ordinal);

        if (sameElement || srcElem is null || dstElem is null)
        {
            return EmitCollectionTerminal(match, sourceAccess);
        }

        // Look for a projection pair for element types
        var nestedPair = allProjectionPairs.FirstOrDefault(p =>
            string.Equals(p.SourceFullName, srcElem, StringComparison.Ordinal) &&
            string.Equals(p.DestFullName, dstElem, StringComparison.Ordinal));

        if (nestedPair is not null && nestedPair.PropertyMatches.Length > 0)
        {
            // Inline the select with member initializer
            var initParts = new List<string>();
            foreach (var prop in nestedPair.PropertyMatches)
            {
                if (prop.ConversionKind == ConversionKind.Dictionary)
                    continue;
                var innerAssignment = EmitProjectionAssignment(prop, "x", allProjectionPairs);
                initParts.Add($"{prop.DestPropertyName} = {innerAssignment}");
            }
            var initBody = string.Join(", ", initParts);
            var selectExpr = $"{sourceAccess}.Select(x => new {dstElem} {{ {initBody} }})";
            return EmitCollectionTerminal(match, selectExpr);
        }

        // Fallback — direct select
        return EmitCollectionTerminal(match, sourceAccess);
    }

    private static string EmitCollectionTerminal(
        PropertyMatchDescriptor match,
        string selectExpr)
    {
        var dstElem = match.DestElementType ?? match.SourceElementType;
        switch (match.DestCollectionKind)
        {
            case CollectionKind.Array:
                return $"{selectExpr}.ToArray()";

            case CollectionKind.HashSet:
                return $"new global::System.Collections.Generic.HashSet<{dstElem}>({selectExpr})";

            case CollectionKind.List:
            default:
                return $"{selectExpr}.ToList()";
        }
    }

    private static string GetNamespace(string fullName)
    {
        var lastDot = fullName.LastIndexOf('.');
        return lastDot >= 0 ? fullName.Substring(0, lastDot) : string.Empty;
    }
}
