title: OpenAutoMapper
description: Native AOT-first object mapper for .NET using Roslyn source generators
remote_theme: just-the-docs/just-the-docs@v0.10.1

url: https://ivahno.github.io/openmapper

color_scheme: dark

aux_links:
  "GitHub": "https://github.com/ivahno/openmapper"
  "NuGet": "https://www.nuget.org/packages/OpenAutoMapper"

aux_links_new_tab: true

nav_sort: case_insensitive

heading_anchors: true

search_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2026 D. Ivahno. <a href=\"https://github.com/ivahno/openmapper/blob/main/LICENSE\">MIT License</a>."
